### ISSUE TITLE
Authentication and page loading fails on production

### ISSUE THREAD

**Issue by cvxluo** [GTBitsOfGood/access-h2o#178]
Our auth system fails on production (https://utility.accessh2o.org/) - currently it has a too many redirects error - on our vercel URL (https://access-h2o.vercel.app), we have a failed to fetch error, but in development (https://access-h2o-frfc72pwc-bitsofgood.vercel.app/login), everything works.

- look at utils/urls to confirm that all the URLs make sense in the context for production
- look at src/contexts/CookieContext.tsx for info on how authentication cookies were set up and src/pages/_app.tsx to see how redirects work
- look at src/components/RouteGuard/RouteGuard.js to see how pages are protected
- look at src/screens/Login/LoginPage.tsx - this is the page that should be redirected to when going to utility.accessh2o.org
- use https://access-h2o-frfc72pwc-bitsofgood.vercel.app/login as a reference for what should be going on
- my branch charlie/table-redirect-fixes was working on this problem - could be useful to reference
- utility.accessh2o.org/login used to load, but had similar authentication issues - most likely due to some URL being misconfigured when making database calls
- baseUrl/app should work as a debug page for authentication 

Contact me for test user credentials to log in (alternatively, you can invoke the signUp function in src/actions/User.js with the .env)

**Comment by SamratSahoo** [comment]
closed by PR #208
