### ISSUE TITLE
Set up login and registration with MongoDB

### ISSUE THREAD

**Issue by cvxluo** [GTBitsOfGood/access-h2o#8]
Revise boilerplate MongoDB actions and models for user authentication. 

### Acceptance Criteria
* Authentication actions properly create/login users
* Authentication is preserved across screens and can be removed through logout

**Comment by nichabosh** [comment]
**Note:** Technically, this issue was resolved prior to me working on it; however, its associated PR (#17) includes additional updates not mentioned in the scope of the task.
